spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    include:
      - mysql

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate.format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    com.zaxxer.hikari.pool.HikariPool: debug
